# Generated by Django 5.1.5 on 2025-01-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilanalysis',
            name='soil_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
